# -*- coding: utf-8 -*-
"""M.SalmanNazeer_Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucaEfR3rw3XNYb90dKPhUTOGGk9t2WzW
"""

# Travel Agent System

def travel_agent():
    flights_database = [
        {"id": "FL101", "departure": "Karachi", "destination": "Lahore", "price": 15000},
        {"id": "FL102", "departure": "Karachi", "destination": "Islamabad", "price": 22000},
        {"id": "FL103", "departure": "Karachi", "destination": "Lahore", "price": 18000},
        {"id": "FL104", "departure": "Lahore", "destination": "Quetta", "price": 12000},
    ]

    departure = input("Enter departure city: ").strip().capitalize()

    destination = input("Enter destination city: ").strip().capitalize()

    available_flights = [
        f for f in flights_database
        if f["departure"].capitalize() == departure and f["destination"].capitalize() == destination
    ]

    if not available_flights:
        print("No flights available")
        return

    print("\n--- Available Flights ---")
    valid_ids = []
    for flight in available_flights:
        print(f"Flight ID: {flight['id']} | Price: PKR {flight['price']}")
        valid_ids.append(flight["id"])

    selected_id = input("\nEnter Flight ID to book: ").strip().upper()

    if selected_id in valid_ids:
        # Display "Flight booked successfully"
        print("\nFlight booked successfully!")
    else:
        print("\nInvalid Flight ID selected.")

travel_agent()